(use ../janet-dotenv/init)
(use spork/test)

(start-suite "Command substitution basics")
(def d (load-as-dict "ONE=$(printf %s one)\nTWO=pre-$(printf %s two)-post\nMANY=$(printf %s a)$(printf %s b)\n"))
(assert (= (get d "ONE") "one"))
(assert (= (get d "TWO") "pre-two-post"))
(assert (= (get d "MANY") "ab"))
(end-suite)

(start-suite "Command substitution quoting")
(def d (load-as-dict "DQ=\"x$(printf %s y)z\"\nTQ=`x$(printf %s y)z`\nSQ='x$(printf %s y)z'\n"))
(assert (= (get d "DQ") "xyz"))
(assert (= (get d "TQ") "xyz"))
(assert (= (get d "SQ") "x$(printf %s y)z"))
(end-suite)

(start-suite "Command substitution with variables")
(os/setenv "CMD_ENV" "from-os")
(def d (load-as-dict "CMD_ENV=from-file\nCOMBO=$CMD_ENV-$(printf %s hi)\nFROM_CMD=$(printenv CMD_ENV)\n"))
(assert (= (get d "COMBO") "from-file-hi"))
(assert (= (string/trim (get d "FROM_CMD")) "from-file"))
(end-suite)

(start-suite "Command substitution in source")
(def d (load-as-dict "source $(printf %s test/dotenvs/child.env)\n"))
(assert (= (get d "CHILD") "child"))
(end-suite)

(start-suite "Command substitution output handling")
(def d (load-as-dict "NL=$(printf a\\n)\nINLINE=$(printf %s ok) # comment\n"))
(assert (= (get d "NL") "a\n"))
(assert (= (get d "INLINE") "ok"))
(end-suite)

(start-suite "Command substitution with interpolate-string")
(assert (= (interpolate-string "pre-$(printf %s post)") "pre-post"))
(end-suite)

(start-suite "Command substitution in load-dotenv")
(os/setenv "DOTENV_CMD" nil)
(def d (load-dotenv "DOTENV_CMD=$(printf %s ok)"))
(assert (= (get d "DOTENV_CMD") "ok"))
(assert (= (os/getenv "DOTENV_CMD") "ok"))
(end-suite)
