(use ../janet-dotenv/init)
(use spork/test)

(start-suite "Comments, whitespace, and empty values")
(def d (load-as-dict "# comment\n  # indented comment\nFOO=bar # inline\nBAR=bar baz # comment\nBAZ=bar#baz\nQUOTED=\"value # not comment\" # comment\nEMPTY=\n  SPACED=ok\n"))
(assert (= (get d "FOO") "bar"))
(assert (= (get d "BAR") "bar baz"))
(assert (= (get d "BAZ") "bar#baz"))
(assert (= (get d "QUOTED") "value # not comment"))
(assert (= (get d "EMPTY") ""))
(assert (= (get d "SPACED") "ok"))
(end-suite)

(start-suite "Export and CRLF")
(def d (load-as-dict "  export EXPORTED=1\r\nPLAIN=2\r\n"))
(assert (= (get d "EXPORTED") "1"))
(assert (= (get d "PLAIN") "2"))
(end-suite)

(start-suite "Local interpolation precedence")
(os/setenv "DOTENV_LOCAL" "from-os")
(def d (load-as-dict "DOTENV_LOCAL=from-file\nCOMBO=$DOTENV_LOCAL"))
(assert (= (get d "COMBO") "from-file"))
(end-suite)

(start-suite "Load-dotenv sets environment")
(os/setenv "DOTENV_SET_TEST" nil)
(def d (load-dotenv "DOTENV_SET_TEST=ok"))
(assert (= (get d "DOTENV_SET_TEST") "ok"))
(assert (= (os/getenv "DOTENV_SET_TEST") "ok"))
(end-suite)

(start-suite "Source interpolation and override")
(def d (load-as-dict "test/dotenvs/parent.env" true))
(assert (= (get d "FILE") "child.env"))
(assert (= (get d "CHILD") "child"))
(assert (= (get d "CHILD_OVERRIDE") "parent"))
(assert (= (get d "PARENT") "parent"))
(end-suite)
