(use ../janet-dotenv/init)
(use spork/test)

(start-suite "Parameter expansion")
(os/setenv "T1" "")
(os/setenv "T2" "val")
(def d (load-as-dict "A1=${T1+X}\nA2=${T2+Y}\nA3=${T1:+Z}\nA4=${T2:+W}\nA5=${T1:-D}\nA6=${T2:-E}\n"))
(assert (= (get d "A1") "X"))
(assert (= (get d "A2") "Y"))
(assert (= (get d "A3") ""))
(assert (= (get d "A4") "W"))
(assert (= (get d "A5") "D"))
(assert (= (get d "A6") "val"))
(end-suite)
